name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Test"
        run: test/bats/bin/bats test

  coverage:
    needs: test
    runs-on: ubuntu-latest
    container: kcov/kcov
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Coverage"
        run: |
          kcov --include-path=src /__w/kcov-coverage/kcov-coverage/coverage test/bats/bin/bats test

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} coverage report
          path: coverage
